### ISSUE TITLE
java.lang.NoClassDefFoundError: com.uphyca.stetho_realm.RealmFilesProvider

### ISSUE THREAD

**Issue by jonathanyee** [uPhyca/stetho-realm#18]
using:
debugCompile 'com.facebook.stetho:stetho:1.0.0'
debugCompile 'com.uphyca:stetho_realm:0.8.0'

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
        classpath 'io.realm:realm-gradle-plugin:0.88.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" } // for MPAndroid Charts
        maven { url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo' }
    }
}
```

```
public class MyDebugApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

        if (BuildConfig.DEBUG) {
            Log.e("RELEASE", "stethos enabled");
            Stetho.initialize(
                    Stetho.newInitializerBuilder(this)
                            .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
                            .enableWebKitInspector(RealmInspectorModulesProvider.builder(this).build())
                            .build());
        }
    }
}
```

```
FATAL EXCEPTION: Stetho-Listener
   java.lang.NoClassDefFoundError: com.uphyca.stetho_realm.RealmFilesProvider
       at com.uphyca.stetho_realm.RealmInspectorModulesProvider.get(RealmInspectorModulesProvider.java:109)
       at com.facebook.stetho.Stetho$BuilderBasedInitializer.getInspectorModules(Stetho.java:252)
       at com.facebook.stetho.Stetho$Initializer.getRegistry(Stetho.java:148)
       at com.facebook.stetho.server.LocalSocketHttpServer.createService(LocalSocketHttpServer.java:232)
       at com.facebook.stetho.server.LocalSocketHttpServer.listenOnAddress(LocalSocketHttpServer.java:158)
       at com.facebook.stetho.server.LocalSocketHttpServer.run(LocalSocketHttpServer.java:134)
       at com.facebook.stetho.Stetho$1.run(Stetho.java:80)
```

**Comment by zaki50** [comment]
We don't support stetho 1.0.0
Please use 1.1 or later(latest is 1.3.1).
