### ISSUE TITLE
Realm 1.0.1 not working 

### ISSUE THREAD

**Issue by jemshit** [uPhyca/stetho-realm#25]
```
Process: com.pordiva.intermail, PID: 12894
                                                                       java.lang.NoClassDefFoundError: Failed resolution of: Lio/realm/internal/ColumnType;
                                                                           at com.uphyca.stetho_realm.Database$2.<clinit>(Database.java:163)
                                                                           at com.uphyca.stetho_realm.Database.flattenRows(Database.java:163)
                                                                           at com.uphyca.stetho_realm.Database.access$300(Database.java:37)
                                                                           at com.uphyca.stetho_realm.Database$1.handleSelect(Database.java:121)
                                                                           at com.uphyca.stetho_realm.Database$1.handleSelect(Database.java:101)
                                                                           at com.uphyca.stetho_realm.RealmPeerManager.executeSQL(RealmPeerManager.java:123)
                                                                           at com.uphyca.stetho_realm.Database.executeSQL(Database.java:100)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:96)
                                                                           at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:67)
                                                                           at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
                                                                           at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
                                                                           at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
                                                                           at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
                                                                           at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
                                                                           at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:46)
                                                                           at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
                                                                           at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:154)
                                                                           at com.facebook.stetho.websocket.WebSocketHandler.handleSecured(WebSocketHandler.java:106)
                                                                           at com.facebook.stetho.server.SecureHttpRequestHandler.handle(SecureHttpRequestHandler.java:52)
                                                                           at org.apache.http.protocol.HttpService.doService(HttpService.java:243)
                                                                           at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:187)
                                                                           at com.facebook.stetho.server.LocalSocketHttpServer$WorkerThread.run(LocalSocketHttpServer.java:233)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.internal.ColumnType" on path: DexPathList[[zip file "/data/app/com.pordiva.intermail-1/base.apk"],nativeLibraryDirectories=[/data/app/com.pordiva.intermail-1/lib/arm, /vendor/lib, /system/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at com.uphyca.stetho_realm.Database$2.<clinit>(Database.java:163) 
                                                                           at com.uphyca.stetho_realm.Database.flattenRows(Database.java:163) 
                                                                           at com.uphyca.stetho_realm.Database.access$300(Database.java:37) 
                                                                           at com.uphyca.stetho_realm.Database$1.handleSelect(Database.java:121) 
                                                                           at com.uphyca.stetho_realm.Database$1.handleSelect(Database.java:101) 
                                                                           at com.uphyca.stetho_realm.RealmPeerManager.executeSQL(RealmPeerManager.java:123) 
                                                                           at com.uphyca.stetho_realm.Database.executeSQL(Database.java:100) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                           at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:96) 
                                                                           at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:67) 
                                                                           at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129) 
                                                                           at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111) 
                                                                           at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87) 
                                                                           at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176) 
                                                                           at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136) 
                                                                           at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:46) 
                                                                           at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45) 
                                                                           at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:154) 
                                                                           at com.facebook.stetho.websocket.WebSocketHandler.handleSecured(WebSocketHandler.java:106) 
                                                                           at com.facebook.stetho.server.SecureHttpRequestHandler.handle(SecureHttpRequestHandler.java:52) 
                                                                           at org.apache.http.protocol.HttpService.doService(HttpService.java:243) 
                                                                           at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:187) 
                                                                           at com.facebook.stetho.server.LocalSocketHttpServer$WorkerThread.run(LocalSocketHttpServer.java:233) 
                                                                        Suppressed: java.lang.ClassNotFoundException: io.realm.internal.ColumnType
                                                                           at java.lang.Class.classForName(Native Method)
                                                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                ... 25 more
                                                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by jemshit** [comment]
ok, i forgot to update version of stetho-realm
