### ISSUE TITLE
java.lang.NoClassDefFoundError: io.realm.internal.LinkView

### ISSUE THREAD

**Issue by gmkado** [uPhyca/stetho-realm#59]
Got this error using Realm 3.7.1:

java.lang.NoClassDefFoundError: io.realm.internal.LinkView
                                                                                          at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
                                                                                          at java.lang.Class.getDexCacheType(Class.java:2551)
                                                                                          at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169)
                                                                                          at java.lang.reflect.Method.getParameterTypes(Method.java:193)
                                                                                          at java.lang.Class.getDeclaredMethods(Class.java:1812)
                                                                                          at com.facebook.stetho.inspector.MethodDispatcher.buildDispatchTable(MethodDispatcher.java:115)
                                                                                          at com.facebook.stetho.inspector.MethodDispatcher.findMethodDispatcher(MethodDispatcher.java:53)
                                                                                          at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:60)
                                                                                          at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
                                                                                          at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
                                                                                          at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
                                                                                          at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
                                                                                          at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
                                                                                          at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44)
                                                                                          at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
                                                                                          at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117)
                                                                                          at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83)
                                                                                          at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
                                                                                          at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
                                                                                          at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
                                                                                          at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
                                                                                          at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
                                                                                          at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
                                                                                          at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)

Looks similar to this https://github.com/uPhyca/stetho-realm/issues/34.  Reverting back to 3.5.0 works fine

**Comment by chim0380** [comment]
I join this bug report
it exception was thrown  in  Realm 3.6 -3.72  when i tried to inspect app in Chrome (with realm 3.72) or on selection db.realm  in Crome (with realm 3.6) .

There wasn't this  exception In Realm 3.5

**Comment by mdumrauf** [comment]
@uPhyca any clues?

**Comment by 4what2do** [comment]
me  too . How to fix it up?

**Comment by RoyXing** [comment]
I have the same question, when i update realm to 3.7.2, it doesn't work and has this crash.

**Comment by 4sskick** [comment]
I think the only way for temporary fix is reverting it to version 3.5

**Comment by Zhuinden** [comment]
See https://github.com/uPhyca/stetho-realm/issues/62#issuecomment-346927558
